language : scala
sudo: required

services:
  - docker

addons:
  hosts:
    - broker1
    - broker2
    - broker3

scala:
  - 2.11.8
  - 2.12.1

cache:
  directories:
  - $HOME/.ivy2
  - $HOME/.sbt

env:
  matrix:
  - KAFKA_TEST_RUNTIME=V_8_2_0      KAFKA_TEST_PROTOCOL=Kafka_0_8
  - KAFKA_TEST_RUNTIME=V_0_9_0_1    KAFKA_TEST_PROTOCOL=Kafka_0_8
  - KAFKA_TEST_RUNTIME=V_0_9_0_1    KAFKA_TEST_PROTOCOL=Kafka_0_9
  - KAFKA_TEST_RUNTIME=V_0_10_0     KAFKA_TEST_PROTOCOL=Kafka_0_8
  - KAFKA_TEST_RUNTIME=V_0_10_0     KAFKA_TEST_PROTOCOL=Kafka_0_9
  - KAFKA_TEST_RUNTIME=V_0_10_0     KAFKA_TEST_PROTOCOL=Kafka_0_10
  - KAFKA_TEST_RUNTIME=V_0_10_1     KAFKA_TEST_PROTOCOL=Kafka_0_8
  - KAFKA_TEST_RUNTIME=V_0_10_1     KAFKA_TEST_PROTOCOL=Kafka_0_9
  - KAFKA_TEST_RUNTIME=V_0_10_1     KAFKA_TEST_PROTOCOL=Kafka_0_10
  - KAFKA_TEST_RUNTIME=V_0_10_1     KAFKA_TEST_PROTOCOL=Kafka_0_10_1
  - KAFKA_TEST_RUNTIME=V_0_10_2     KAFKA_TEST_PROTOCOL=Kafka_0_8
  - KAFKA_TEST_RUNTIME=V_0_10_2     KAFKA_TEST_PROTOCOL=Kafka_0_9
  - KAFKA_TEST_RUNTIME=V_0_10_2     KAFKA_TEST_PROTOCOL=Kafka_0_10
  - KAFKA_TEST_RUNTIME=V_0_10_2     KAFKA_TEST_PROTOCOL=Kafka_0_10_1
  - KAFKA_TEST_RUNTIME=V_0_10_2     KAFKA_TEST_PROTOCOL=Kafka_0_10_2
  - KAFKA_TEST_RUNTIME=V_0_11_0     KAFKA_TEST_PROTOCOL=Kafka_0_8
  - KAFKA_TEST_RUNTIME=V_0_11_0     KAFKA_TEST_PROTOCOL=Kafka_0_9
  - KAFKA_TEST_RUNTIME=V_0_11_0     KAFKA_TEST_PROTOCOL=Kafka_0_10
  - KAFKA_TEST_RUNTIME=V_0_11_0     KAFKA_TEST_PROTOCOL=Kafka_0_10_1
  - KAFKA_TEST_RUNTIME=V_0_11_0     KAFKA_TEST_PROTOCOL=Kafka_0_10_2
  - KAFKA_TEST_RUNTIME=V_1_0_0      KAFKA_TEST_PROTOCOL=Kafka_0_8
  - KAFKA_TEST_RUNTIME=V_1_0_0      KAFKA_TEST_PROTOCOL=Kafka_0_9
  - KAFKA_TEST_RUNTIME=V_1_0_0      KAFKA_TEST_PROTOCOL=Kafka_0_10
  - KAFKA_TEST_RUNTIME=V_1_0_0      KAFKA_TEST_PROTOCOL=Kafka_0_10_1
  - KAFKA_TEST_RUNTIME=V_1_0_0      KAFKA_TEST_PROTOCOL=Kafka_0_10_2


jdk:
  - oraclejdk8


script:
  - sbt ++$TRAVIS_SCALA_VERSION -Dfile.encoding=UTF8 test


